export const APPLICATION_STATUS = Object.freeze({
  APPLIED: 'Applied',
  SHORTLISTED: 'Shortlisted',
  INTERVIEW_SCHEDULED: 'Interview Scheduled',
  SELECTED: 'Selected',
  REJECTED: 'Rejected',
});

export const APPLICATION_STATUS_VALUES = Object.values(APPLICATION_STATUS);

// Status flow: Applied -> Shortlisted -> Interview Scheduled -> Selected (or Rejected at any stage)
export const ALLOWED_STATUS_TRANSITIONS = Object.freeze({
  [APPLICATION_STATUS.APPLIED]: [APPLICATION_STATUS.SHORTLISTED, APPLICATION_STATUS.REJECTED],
  [APPLICATION_STATUS.SHORTLISTED]: [APPLICATION_STATUS.INTERVIEW_SCHEDULED, APPLICATION_STATUS.REJECTED],
  [APPLICATION_STATUS.INTERVIEW_SCHEDULED]: [APPLICATION_STATUS.SELECTED, APPLICATION_STATUS.REJECTED],
  [APPLICATION_STATUS.SELECTED]: [],
  [APPLICATION_STATUS.REJECTED]: [],
});
